[package]
name = "pathfinder"
version = "0.1.1"
authors = ["Thomas Sauvajon <thomas@sauvajon.tech>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.16"
wasm-bindgen = "0.2"
rand = "0.7.3"
